# -*- mode: ruby -*-
# vi: set ft=ruby :

def enabled?(var)
  val = ENV[var.upcase]
  if val == nil
    return false
  elsif val.empty?
    return false
  # We could definitely be more user-friendly and accept "no", "0",
  # etc. as false, but that logic is hard to implement in the Makefile
  # and I'd like to be consistent.
  else
    return true
  end
end

Vagrant.configure("2") do |config|
  config.vagrant.plugins = ["vagrant-disksize", "vagrant-vbguest"]

  config.vm.provider "virtualbox" do |v|
    v.gui = !enabled?("headless")
  end

  config.vm.define "sender", primary: true do |sender|
    sender.vm.hostname = "sender"
    if enabled?("routers")
      sender.vm.network "private_network", ip: "192.168.66.10"
      sender.vm.provision "shell", run: "always", inline: "sudo route del default"
      sender.vm.provision "shell", run: "always", inline: "sudo route add default gw 192.168.66.100"
    else
      sender.vm.network "private_network", ip: "192.168.33.10"
    end
  end

  config.vm.define "receiver" do |receiver|
    receiver.vm.network "private_network", ip: "192.168.33.11"
    receiver.vm.hostname = "receiver"
    if enabled?("routers")
      receiver.vm.provision "shell", run: "always", inline: "sudo route del default"
      receiver.vm.provision "shell", run: "always", inline: "sudo route add default gw 192.168.33.101"
    end
  end

  if enabled?("routers")
    config.vm.define "sender-router" do |router|
      router.vm.network "private_network", ip: "192.168.50.100"
      router.vm.network "private_network", ip: "192.168.66.100"
      router.vm.hostname = "sender-router"
      router.vm.provision "shell", run: "always", inline: "sudo route add -net 192.168.33.0/24 gw 192.168.50.101 dev enp0s8"
      router.vm.provision "shell", run: "always", inline: "sudo sysctl -w net.ipv4.ip_forward=1"
    end

    config.vm.define "receiver-router" do |router|
      router.vm.network "private_network", ip: "192.168.50.101"
      router.vm.network "private_network", ip: "192.168.33.101"
      router.vm.hostname = "receiver-router"
      router.vm.provision "shell", run: "always", inline: "sudo route add -net 192.168.66.0/24 gw 192.168.50.100 dev enp0s8"
      router.vm.provision "shell", run: "always", inline: "sudo sysctl -w net.ipv4.ip_forward=1"
    end
  end

  config.vm.box = "ubuntu/bionic64"
  config.disksize.size = "50GB"
  config.vm.provision :shell, path: "scripts/provision.bash"
  config.vm.provision "shell", run: "always", inline: "sudo sysctl net.ipv4.ip_no_pmtu_disc=1"

  if File.directory? "../../juniper-linux"
    config.vm.synced_folder "../../juniper-linux", "/linux"
  elsif File.directory? "../../linux"
    config.vm.synced_folder "../../linux", "/linux"
  end
end
