# -*- mode: ruby -*-
# vi: set ft=ruby :

["vagrant-disksize", "vagrant-reload", "vagrant-vbguest"].each do |plugin|
  unless Vagrant.has_plugin?(plugin)
    system("vagrant plugin install #{plugin}")
  end
end

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.gui = false
  end

  config.vm.define "sender", primary: true do |sender|
    sender.vm.network "private_network", ip: "fde4:8dba:82e0::c4", netmask: "64", virtualbox__intnet: "nw1"
    sender.vm.hostname = "sender"
    sender.vm.provision "shell", run: "always", inline: "sudo route -A inet6 add default gw fde4:8dba:82e0::c5"
  end

  config.vm.define "receiver" do |receiver|
    receiver.vm.network "private_network", ip: "fde4:8dba:82e1::c4", mac: "080027a1ca9a", netmask: "64", virtualbox__intnet: "nw2"
    receiver.vm.hostname = "receiver"
    receiver.vm.provision "shell", run: "always", inline: "sudo route -A inet6 add default gw fde4:8dba:82e1::c5"
  end

  config.vm.define "router" do |router|
    router.vm.network "private_network", ip: "fde4:8dba:82e0::c5", netmask: "64", virtualbox__intnet: "nw1"
    router.vm.network "private_network", ip: "fde4:8dba:82e1::c5", netmask: "64", virtualbox__intnet: "nw2"
    router.vm.hostname = "router"
    router.vm.provision "shell", run: "always", inline: "sudo sysctl -w net.ipv6.conf.all.forwarding=1"
  end

  config.vm.box = "ubuntu/bionic64"
  config.disksize.size = '50GB'

  config.vm.provision :shell, path: "scripts/provision.bash"
  config.vm.provision :reload

end
