# -*- mode: ruby -*-
# vi: set ft=ruby :

["vagrant-disksize", "vagrant-reload", "vagrant-vbguest"].each do |plugin|
  unless Vagrant.has_plugin?(plugin)
    system("vagrant plugin install #{plugin}")
  end
end

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.gui = false
  end

  config.vm.define "sender", primary: true do |sender|
    sender.vm.network "private_network", ip: "fde4:8dba:82e1::c4"
    sender.vm.hostname = "sender"
  end
  config.vm.define "receiver" do |receiver|
    receiver.vm.network "private_network", ip: "fde4:8dba:82e1::c5"
    receiver.vm.hostname = "receiver"
  end

  config.vm.box = "ubuntu/bionic64"
  config.disksize.size = '50GB'

  config.vm.provision :shell, path: "scripts/provision.bash"
  config.vm.provision :reload

end
